parent_paths:
- name: movie
  path: /archive/PLEX/movies/
- name: archive_tvshow
  path: /archive/PLEX/tvshows/
- name: wcc6y7pdn1r3
  path: /mnt/d/tvshows/
- name: bu1
  path: /bu/tv1
- name: bu2
  path: /bu/movie1
